server:
  port: 8110
  servlet:
    context-path: /eureka-client-2
spring:
  application:
    name: spring-cloud-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html